name: frontend
description: Main app
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.32.0 <2.0.0'

dependencies:
  angular: 5.0.0-alpha+6
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  sass_builder: ^1.1.2

dev_dependencies:
  #angular_test: ^1.0.0
  test: ^0.12.0
  mockito: ^3.0.0-alpha
  build_runner: ^0.7.12
  build_web_compilers: ^0.3.0

dependency_overrides:
  # Necessary with angular: 5.0.0-alpha+ dependency.
  analyzer: ^0.31.0-alpha.1
