name: frontend
description: Main app
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.59.0 <2.0.0'

dependencies:
  rxdart: ^0.16.0+1
  angular: 5.0.0-alpha+13
  angular_router: 2.0.0-alpha+12
  sass_builder: ^1.1.4
  w4p_core:
    path: ../w4p_core
  w4p_components:
    path: ../w4p_components

dev_dependencies:
  #angular_test: ^1.0.0
  test: ^0.12.0
  mockito: ^3.0.0-alpha
  build_runner: ^0.8.6
  build_web_compilers: ^0.4.0

dependency_overrides:
  # Necessary with angular: 5.0.0-alpha+ dependency.
  analyzer: ^0.32.2
