name: w4p_components
description: Component kit
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.67.0 <2.0.0'

dependencies:
  rxdart: ^0.16.0+1
  angular: ^5.0.0-alpha+13
  browser: ^0.10.0
  sass_builder: ^2.1.0
  w4p_core:
    path: ../w4p_core

dev_dependencies:
  #angular_test: ^1.0.0
  test: ^0.12.0
  mockito: ^3.0.0-alpha
  build_runner: ^0.8.4
  build_web_compilers: ^0.4.0

dependency_overrides:
  # Necessary with angular: 5.0.0-alpha+ dependency.
  analyzer: ^0.31.2-alpha.2

